print("Once upon a time")
print('we decided to code')
print("in a land far, far away")
print("there was a beautiful princess")
print("named Rose.")
print("She lived in a castle")
print("with her best friend,")
print("a dragon named Scorch.")
print("They had many grand adventures")
print("together, and everyone")
print("in the kingdom loved them.")
